spring:
  application:
    name: texas-holdem-demo
  mvc:
    servlet:
      path: ${BASE_URL:/}
server:
  port: 8080
gamerule:
  default-initial-chip: ${GAMERULE_INITIAL_CHIP:5000}
  default-small-blind-bet: ${GAMERULE_SMALL_BLIND_BET:5}
  default-reflection-time: ${GAMERULE_REFLECTION_TIME:120000}
  default-suit-range: ${GAMERULE_SUIT_RANGE:4}
  default-rank-range: ${GAMERULE_RANK_RANGE:13}
api:
 error-redirect: ${ERROR_REDIRECT:}
 websocket-endpoint: ${WEBSOCKET_ENDPOINT:}